services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    build:
      context: ./backend
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
