services:
  api:
    build: .
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
