version: '3.9'

services:
  api:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-votemanager}
      POSTGRES_USER: ${POSTGRES_USER:-votemanager}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
