"""add user_id FK to votes

Revision ID: 7aa43b0b70b7
Revises: b4b77f80e1bd
Create Date: 2025-06-22 09:37:05.640437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa43b0b70b7'
down_revision: Union[str, Sequence[str], None] = 'b4b77f80e1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'votes',
        sa.Column('user_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        'fk_votes_user_id_users',
        'votes', 'users',
        ['user_id'], ['id'],
        ondelete='CASCADE'
    )

    op.execute(
        "UPDATE votes SET user_id = 1 WHERE user_id IS NULL"
    )

    op.alter_column(
        'votes',
        'user_id',
        existing_type=sa.Integer(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'user_id')
    # ### end Alembic commands ###
